### ISSUE TITLE
Is this efi perfect ?

### ISSUE THREAD

**Issue by thorxh** [jojo176/TerransForce-T5SKYLAKE-67SH1-Hackintosh-OpenCore#1]
Is this efi perfect ?

**Comment by jojo176** [comment]
Can't Sleep

**Comment by jojo176** [comment]
> Is this efi perfect ?

Can't Sleep

**Comment by thorxh** [comment]
> > Is this efi perfect ?
> 
> Can't Sleep

What needs attention？

**Comment by jojo176** [comment]
> > > Is this efi perfect ?
> > 
> > 
> > Can't Sleep
> 
> What needs attention？
If your computer is the same as mine or has the same main configuration, no special attention is required. I will modify the configuration file for you to debug

**Comment by thorxh** [comment]
你的镜像文件是什么？官方的吗？我用了黑果小兵的，但是刚安装的时候就报错了

**Comment by jojo176** [comment]
> 你的镜像文件是什么？官方的吗？我用了黑果小兵的，但是刚安装的时候就报错了
我是一开始的是黑果制作的，后面在AppStore升级了的。

**Comment by thorxh** [comment]
> > 你的镜像文件是什么？官方的吗？我用了黑果小兵的，但是刚安装的时候就报错了
> > 我是一开始的是黑果制作的，后面在AppStore升级了的。

你的bios有没有什么特殊的设置？

**Comment by jojo176** [comment]
> > > 你的镜像文件是什么？官方的吗？我用了黑果小兵的，但是刚安装的时候就报错了
> > > 我是一开始的是黑果制作的，后面在AppStore升级了的。
> 
> 你的bios有没有什么特殊的设置？

没有，你要是同款机型应该能用的。

**Comment by thorxh** [comment]
安装上了，谢了

**Comment by thorxh** [comment]
我的电脑可以休眠，你的不可以吗？是什么状况？

**Comment by jojo176** [comment]
> 我的电脑可以休眠，你的不可以吗？是什么状况？

😂😂😂 这个我还没有认真去做补丁什么的，就不是很在意，能休眠就挺好的
